import 'dotenv/config';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildHomePayload } from '../src/server/catalogue-api';
import { createR2Storage } from '../src/server/r2-storage';
import { publishManagedImageFile, summarizeManagedImagePublication, type ManagedImagePublicationResult } from '../src/server/managed-images';
import { writeFileAtomically } from '../src/utils/atomic-file';
import { resolveImageUrl } from '../src/utils/image-url';
import { getHomepageManifestIds } from '../src/utils/homepage-images';
import { detectImageMagickExecutable } from '../src/server/image-processing';

const projectRoot = process.cwd();
const sourceRoot = path.join(projectRoot, 'public');
const outputDirectory = path.join(sourceRoot, 'images', 'optimized', 'posters');
const manifestPath = path.join(projectRoot, 'src', 'data', 'homepage-poster-ids.ts');
const publishR2 = process.argv.includes('--publish-r2');
const previouslyPublishedIds = new Set<string>((() => {
  try { return [...readFileSync(manifestPath, 'utf8').matchAll(/'([0-9]+)',/g)].map((match) => match[1]!); } catch { return []; }
})());

const homepage = buildHomePayload();
const posterUrls = [...homepage.comingSoon, ...homepage.discovery]
  .map((movie) => movie.posterUrl)
  .filter((url): url is string => /^\/images\/posters\/\d+(?:-[^/]+)?\.jpg$/.test(url));

const posters = new Map<string, string>();
for (const url of posterUrls) {
  const match = url.match(/^\/images\/posters\/(\d+)(?:-[^/]+)?\.jpg$/);
  if (match) posters.set(match[1], url);
}

mkdirSync(outputDirectory, { recursive: true });

const imageMagickExecutable = detectImageMagickExecutable();
const imageMagickAvailable = Boolean(imageMagickExecutable);
if (!imageMagickAvailable) {
  console.warn('[homepage-posters] ImageMagick unavailable; keeping existing derivatives and using original posters when needed.');
}
if (publishR2 && !imageMagickAvailable) throw new Error('[homepage-posters] ImageMagick is required for homepage R2 publication.');

const generatedIds: string[] = [];
let downloadedSourceDirectory: string | undefined;
try {
  for (const [id, url] of posters) {
    let sourcePath = path.join(sourceRoot, url.slice(1));
    const outputPath = path.join(outputDirectory, `${id}-320.webp`);
    if (!existsSync(sourcePath) && publishR2) {
      const sourceUrl = resolveImageUrl(url);
      if (!sourceUrl) throw new Error(`[homepage-posters] Could not resolve source image URL for ${url}`);
      const response = await fetch(sourceUrl);
      if (!response.ok) throw new Error(`[homepage-posters] Failed to fetch ${sourceUrl}: HTTP ${response.status}`);
      downloadedSourceDirectory ||= mkdtempSync(path.join(os.tmpdir(), 'xmasdb-homepage-source-'));
      sourcePath = path.join(downloadedSourceDirectory, path.basename(url));
      writeFileSync(sourcePath, Buffer.from(await response.arrayBuffer()));
    }
    if (!existsSync(sourcePath)) {
      console.warn(`[homepage-posters] Missing source image: ${sourcePath}`);
      continue;
    }

    if (imageMagickAvailable) {
      const temporaryPath = `${outputPath}.${process.pid}.tmp`;
      try {
        execFileSync(imageMagickExecutable!, [sourcePath, '-resize', '320x480', '-strip', '-quality', '82', `webp:${temporaryPath}`], { stdio: 'inherit' });
        renameSync(temporaryPath, outputPath);
      } finally {
        try { unlinkSync(temporaryPath); } catch { /* already renamed or absent */ }
      }
    }

    if (existsSync(outputPath)) generatedIds.push(id);
  }
} finally {
  if (downloadedSourceDirectory) rmSync(downloadedSourceDirectory, { recursive: true, force: true });
}

console.log(`[homepage-posters] Generated ${generatedIds.length} derivatives at 320x480 WebP.`);

if (publishR2) {
  const storage = createR2Storage();
  const publicationResults: ManagedImagePublicationResult[] = [];
  for (const id of generatedIds) {
    publicationResults.push(await publishManagedImageFile(`/images/optimized/posters/${id}-320.webp`, `/images/optimized/posters/${id}-320.webp`, { storage }));
  }
  const summary = summarizeManagedImagePublication(publicationResults);
  console.log(`[homepage-posters] R2 publication: uploaded=${summary.uploaded} skipped=${summary.skipped} verified=${summary.verified}`);
}

generatedIds.sort((a, b) => Number(a) - Number(b));
const manifestIds = getHomepageManifestIds(posters.keys(), previouslyPublishedIds, publishR2);
await writeFileAtomically(manifestPath, `/**\n * Generated by scripts/generate-homepage-posters.ts before each production build.\n * Keep this file in source control so the client and generated image derivatives\n * stay in sync in local development and after deployment.\n */\nconst homepagePosterIds = new Set<string>([\n${manifestIds.map((id) => `  '${id}',`).join('\n')}\n]);\n\nexport default homepagePosterIds;\n`);

if (publishR2) console.log(`[homepage-posters] Manifest updated: ${manifestIds.length} IDs`);
