import 'dotenv/config';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, unlinkSync, writeFileSync, renameSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildBirthdaysPayload } from '../src/server/catalogue-api';
import { createR2Storage } from '../src/server/r2-storage';
import { publishManagedImageFile, summarizeManagedImagePublication, type ManagedImagePublicationResult } from '../src/server/managed-images';
import { resolveImageUrl } from '../src/utils/image-url';
import { buildImageMagickCommand, detectImageMagickExecutable } from '../src/server/image-processing';

const projectRoot = process.cwd();
const publicRoot = path.join(projectRoot, 'public');
const outputDirectory = path.join(publicRoot, 'images', 'birthdays');
const manifestPath = path.join(projectRoot, 'src', 'data', 'birthday-actor-ids.ts');
const publishR2 = process.argv.includes('--publish-r2');
const existingIds = new Set<string>((() => {
  try { return [...readFileSync(manifestPath, 'utf8').matchAll(/'([0-9]+)',/g)].map((match) => match[1]!); } catch { return []; }
})());

const birthdayIds = new Set(buildBirthdaysPayload().actors.filter((actor) => actor.photoUrl).map((actor) => String(actor.tmdbPersonId)));
const imageMagickExecutable = detectImageMagickExecutable();
if (!imageMagickExecutable) throw new Error('[actor-portraits] ImageMagick is required to generate actor derivatives.');
mkdirSync(outputDirectory, { recursive: true });

let downloadedSourceDirectory: string | undefined;
const generatedIds = new Set<string>();
const missingSourceIds: string[] = [];
try {
  for (const id of birthdayIds) {
    const sourceUrl = `/images/people/${id}.webp`;
    let sourcePath = path.join(publicRoot, sourceUrl.slice(1));
    if (!existsSync(sourcePath) && publishR2) {
      const remoteUrl = resolveImageUrl(sourceUrl);
      if (!remoteUrl) {
        missingSourceIds.push(id);
        continue;
      }
      const response = await fetch(remoteUrl);
      if (!response.ok) {
        missingSourceIds.push(id);
        continue;
      }
      downloadedSourceDirectory ||= mkdtempSync(path.join(os.tmpdir(), 'xmasdb-actor-source-'));
      sourcePath = path.join(downloadedSourceDirectory, `${id}.webp`);
      writeFileSync(sourcePath, Buffer.from(await response.arrayBuffer()));
    }
    if (!existsSync(sourcePath)) {
      if (publishR2) missingSourceIds.push(id);
      continue;
    }
    const outputPath = path.join(outputDirectory, `${id}-216.webp`);
    const temporaryPath = `${outputPath}.${process.pid}.tmp`;
    try {
      const command = buildImageMagickCommand(imageMagickExecutable, 'convert', [sourcePath, '-resize', '216x216^', '-gravity', 'center', '-extent', '216x216', '-strip', '-quality', '82', `webp:${temporaryPath}`]);
      execFileSync(command.executable, command.args, { stdio: 'inherit' });
      renameSync(temporaryPath, outputPath);
      generatedIds.add(id);
    } finally {
      try { unlinkSync(temporaryPath); } catch { /* already renamed or absent */ }
    }
  }
} finally {
  if (downloadedSourceDirectory) rmSync(downloadedSourceDirectory, { recursive: true, force: true });
}

if (publishR2 && missingSourceIds.length > 0) {
  throw new Error(`[actor-portraits] Could not obtain source portraits for ${missingSourceIds.length} birthday actors: ${missingSourceIds.join(', ')}`);
}

if (publishR2) {
  const storage = createR2Storage();
  const publicationResults: ManagedImagePublicationResult[] = [];
  for (const id of generatedIds) {
    const filePath = path.join(outputDirectory, `${id}-216.webp`);
    if (existsSync(filePath)) {
      publicationResults.push(await publishManagedImageFile(`/images/birthdays/${id}-216.webp`, `/images/birthdays/${id}-216.webp`, { storage, overwriteExisting: false }));
      existingIds.add(id);
    }
  }
  const summary = summarizeManagedImagePublication(publicationResults);
  console.log(`[actor-portraits] R2 publication: uploaded=${summary.uploaded} skipped=${summary.skipped} verified=${summary.verified}`);
}

const sortedIds = [...existingIds].sort((left, right) => Number(left) - Number(right));
writeFileSync(manifestPath, `/** Generated by scripts/generate-actor-portraits.ts. */\nconst birthdayActorIds = new Set<string>([\n${sortedIds.map((id) => `  '${id}',`).join('\n')}\n]);\n\nexport default birthdayActorIds;\n`);
console.log(`[actor-portraits] ${existingIds.size} available 216px actor derivatives (${generatedIds.size} generated locally${publishR2 ? ', published, and enabled' : '; run with --publish-r2 to enable'}).`);
