import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { buildHomePayload } from '../src/server/catalogue-api';

const projectRoot = process.cwd();
const sourceRoot = path.join(projectRoot, 'public');
const outputDirectory = path.join(sourceRoot, 'images', 'optimized', 'posters');
const manifestPath = path.join(projectRoot, 'src', 'data', 'homepage-poster-ids.ts');

const homepage = buildHomePayload();
const posterUrls = [...homepage.comingSoon, ...homepage.discovery]
  .map((movie) => movie.posterUrl)
  .filter((url): url is string => /^\/images\/posters\/\d+(?:-[^/]+)?\.jpg$/.test(url));

const posters = new Map<string, string>();
for (const url of posterUrls) {
  const match = url.match(/^\/images\/posters\/(\d+)(?:-[^/]+)?\.jpg$/);
  if (match) posters.set(match[1], url);
}

mkdirSync(outputDirectory, { recursive: true });

for (const fileName of readdirSync(outputDirectory)) {
  if (/^\d+-320\.webp$/.test(fileName)) unlinkSync(path.join(outputDirectory, fileName));
}

const generatedIds: string[] = [];
for (const [id, url] of posters) {
  const sourcePath = path.join(sourceRoot, url.slice(1));
  const outputPath = path.join(outputDirectory, `${id}-320.webp`);
  if (!existsSync(sourcePath)) {
    console.warn(`[homepage-posters] Missing source image: ${sourcePath}`);
    continue;
  }

  execFileSync('magick', [sourcePath, '-resize', '320x480', '-strip', '-quality', '82', outputPath], { stdio: 'inherit' });
  generatedIds.push(id);
}

generatedIds.sort((a, b) => Number(a) - Number(b));
writeFileSync(manifestPath, `/**\n * Generated by scripts/generate-homepage-posters.ts before each production build.\n * Keep this file in source control so the client and generated image derivatives\n * stay in sync in local development and after deployment.\n */\nconst homepagePosterIds = new Set<string>([\n${generatedIds.map((id) => `  '${id}',`).join('\n')}\n]);\n\nexport default homepagePosterIds;\n`);

console.log(`[homepage-posters] Generated ${generatedIds.length} derivatives at 320x480 WebP.`);
