/**
 * Generated by scripts/generate-homepage-posters.ts before each production build.
 * Keep this file in source control so the client and generated image derivatives
 * stay in sync in local development and after deployment.
 */
const homepagePosterIds = new Set<string>([
  '299579',
  '420967',
  '474987',
  '549301',
  '604553',
  '627482',
  '881245',
  '1027329',
  '1033385',
  '1142715',
  '1180367',
  '1325912',
  '1652348',
  '1701085',
  '1729134',
  '1772765',
  '1773006',
  '1773195',
]);

export default homepagePosterIds;
