/**
 * Generated by scripts/generate-homepage-posters.ts before each production build.
 * Keep this file in source control so the client and generated image derivatives
 * stay in sync in local development and after deployment.
 */
const homepagePosterIds = new Set<string>([
  '147132',
  '365762',
  '420967',
  '474987',
  '569982',
  '604553',
  '744940',
  '826451',
  '874244',
  '1341132',
  '1491727',
  '1652348',
  '1701085',
  '1729134',
  '1772765',
  '1773006',
  '1773195',
]);

export default homepagePosterIds;
