/**
 * Generated by scripts/generate-homepage-posters.ts before each production build.
 * Keep this file in source control so the client and generated image derivatives
 * stay in sync in local development and after deployment.
 */
const homepagePosterIds = new Set<string>([
  '299579',
  '339543',
  '420967',
  '474987',
  '550648',
  '626296',
  '744925',
  '744941',
  '878417',
  '911826',
  '1137856',
  '1418422',
  '1652348',
  '1701085',
  '1729134',
  '1772765',
  '1773006',
  '1773195',
]);

export default homepagePosterIds;
