/** Generated by scripts/generate-actor-portraits.ts. */
const optimizedActorIds = new Set<string>([
  '4568',
  '22082',
  '31363',
  '33669',
  '35472',
  '43265',
  '43426',
  '62909',
  '78501',
  '82943',
  '92856',
  '104646',
  '122888',
  '134673',
  '151975',
  '168750',
  '169469',
  '218923',
  '589182',
  '1233560',
  '1292329',
  '1751311',
  '2081445',
  '2120306',
]);

export default optimizedActorIds;
